name: 'GitHub Actions Lockfile'
description: 'Generate and verify lockfiles for GitHub Actions dependencies'
author: 'gjtorikian'

branding:
  icon: 'lock'
  color: 'blue'

inputs:
  mode:
    description: 'Mode to run in: generate or verify'
    required: true
    default: 'verify'
  token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  workflows:
    description: 'Path to workflows directory'
    required: false
    default: '.github/workflows'
  output:
    description: 'Path to lockfile'
    required: false
    default: '.github/actions.lock.json'
  comment:
    description: 'Post a PR comment when verification fails (only in verify mode)'
    required: false
    default: 'true'

outputs:
  changed:
    description: 'Whether the lockfile changed (for generate mode)'

runs:
  using: 'node24'
  main: 'dist/index.js'
